export const collectionData = [
  {
    id: 1,
    name: "Alex Ca.",
    subName: "By Alex.",
    mail: "@Alex",
    volume: "8,456",
    day: "+ 27.78%",
    price: "3,5",
    owners: "2.2K",
    items: "500",
    image: "assets/icons/SunGlass1.png",
    follow: true,
    count: "1",
  },
  {
    id: 2,
    name: "John Doe",
    subName: "By John.",
    mail: "@John",
    volume: "7,892",
    day: "+ 15.32%",
    price: "2.8",
    owners: "1.8K",
    items: "450",
    image: "assets/icons/SunGlass2.png",
    follow: true,
    count: "2",
  },
  {
    id: 3,
    name: "Sarah Smith",
    subName: "By Sarah.",
    mail: "@Sarah",
    volume: "6,712",
    day: "+ 21.17%",
    price: "3.2",
    owners: "1.5K",
    items: "400",
    image: "assets/icons/SunGlass3.png",
    follow: true,
    count: "2",
  },
  {
    id: 4,
    name: "Mike Johnson",
    subName: "By Mike.",
    mail: "@Mike",
    volume: "9,345",
    day: "+ 30.05%",
    price: "4.1",
    owners: "2.5K",
    items: "550",
    image: "assets/icons/SunGlass4.png",
    follow: false,
    count: "3",
  },
  {
    id: 5,
    name: "Emma Brown",
    subName: "By Emma.",
    mail: "@Emma",
    volume: "7,621",
    day: "+ 18.94%",
    price: "2.9",
    owners: "1.7K",
    items: "480",
    image: "assets/icons/SunGlass1.png",
    follow: true,
    count: "2",
  },
  {
    id: 6,
    name: "David Wilson",
    subName: "By David.",
    mail: "@David",
    volume: "8,912",
    day: "+ 25.81%",
    price: "3.6",
    owners: "2.0K",
    items: "520",
    image: "assets/icons/SunGlass2.png",
    follow: false,
    count: "3",
  },
];

export const RecentData = [
  {
    id: 1,
    name: "Alex Ca.",
    subName: "Alex.",
    volume: "8,456",
    day: "+23,00%",
    image: "assets/icons/SunGlass1.png",
    minus: true,
    count: "1",
    procent: "+23,00%",
  },
  {
    id: 2,
    name: "Juliya S.",
    subName: "JuliyaS",
    volume: "5,327",
    day: "-32,01%",
    image: "assets/icons/SunGlass2.png",
    minus: false,
    count: "1",
    procent: "+23,00%",
  },
];